#!/bin/sh
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Boot picom
picom --daemon --experimental-backends &> /dev/null

# Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Set background
feh --bg-fill --no-fehbg $SCRIPTPATH/background.jpg

# Conky (not yet configured)
#~/.config/conky/start-conky.sh

# Polybar
polybar -c $SCRIPTPATH/polybar.ini mainbar &> /dev/null &
